export const EMPLOYEE_SPECIALTY_ALL = 'ALL';

export const EMPLOYEE_BOOKING_ALL = 'ALL';
export const EMPLOYEE_BOOKING_ACCEPTING = 'ACCEPTING';
export const EMPLOYEE_BOOKING_NOT_ACCEPTING = 'NOT_ACCEPTING';
