export enum NotificationType {
  // Booking
  APPOINTMENT_CREATED = "APPOINTMENT_CREATED",
  APPOINTMENT_CONFIRMED = "APPOINTMENT_CONFIRMED",
  APPOINTMENT_CANCELLED = "APPOINTMENT_CANCELLED",
  APPOINTMENT_RESCHEDULED = "APPOINTMENT_RESCHEDULED",
  APPOINTMENT_REMINDER = "APPOINTMENT_REMINDER",

  // Pet health
  PET_VACCINE_DUE = "PET_VACCINE_DUE",
  PET_VACCINE_OVERDUE = "PET_VACCINE_OVERDUE",
  PET_CHECKUP_REMINDER = "PET_CHECKUP_REMINDER",
  PET_HEALTH_RECORD_UPDATED = "PET_HEALTH_RECORD_UPDATED",

  // Payment
  PAYMENT_SUCCESS = "PAYMENT_SUCCESS",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  REFUND_PROCESSED = "REFUND_PROCESSED",

  // Clinic / staff
  NEW_BOOKING_ASSIGNED = "NEW_BOOKING_ASSIGNED",
  STAFF_SCHEDULE_UPDATED = "STAFF_SCHEDULE_UPDATED",

  // System
  SYSTEM_ANNOUNCEMENT = "SYSTEM_ANNOUNCEMENT",
  SYSTEM_MAINTENANCE = "SYSTEM_MAINTENANCE",
  POLICY_UPDATED = "POLICY_UPDATED",
}

export interface CreateNotificationInput {
  type: NotificationType;
  title: string;
  message: string;
  data?: Record<string, any>;
  senderId?: string;
  priority?: number;
  recipientIds: string[];
}
